# Generated by Django 6.0.1 on 2026-01-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number for WhatsApp notifications', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='Receive SMS notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_notifications',
            field=models.BooleanField(default=False, help_text='Receive WhatsApp notifications'),
        ),
    ]
