# Generated by Django 5.2.10 on 2026-01-26 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_cart_cartitem'),
        ('services', '0011_service_cost_price_alter_service_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Expense description', max_length=255)),
                ('category', models.CharField(choices=[('server', 'Server/Hosting Costs'), ('domain', 'Domain Registry Costs'), ('license', 'Software Licenses'), ('cpanel', 'cPanel/Control Panel'), ('ssl', 'SSL Certificates'), ('bandwidth', 'Bandwidth/CDN'), ('marketing', 'Marketing & Advertising'), ('salary', 'Salaries & Wages'), ('office', 'Office & Utilities'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring', models.CharField(choices=[('none', 'One-time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='none', max_length=20)),
                ('vendor', models.CharField(blank=True, help_text='Provider/Vendor name (e.g., cPanel Inc, Namecheap)', max_length=255, null=True)),
                ('expense_date', models.DateField(help_text='Date of expense')),
                ('next_due_date', models.DateField(blank=True, help_text='Next payment due for recurring', null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Invoice/Reference number from vendor', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, help_text='Associated service (e.g., cPanel license for hosting)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='services.service')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'ordering': ['-expense_date'],
            },
        ),
    ]
