# Generated by Django 6.0.1 on 2026-01-10 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('cpanel', 'cPanel'), ('directadmin', 'DirectAdmin'), ('cloudflare', 'Cloudflare'), ('aws', 'AWS'), ('digitalocean', 'DigitalOcean'), ('other', 'Other')], max_length=50)),
                ('name', models.CharField(help_text='Friendly name for this integration', max_length=255)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('encrypted_password', models.TextField(blank=True, null=True)),
                ('encrypted_api_token', models.TextField(blank=True, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_credentials', to='clients.client')),
            ],
            options={
                'verbose_name': 'integration credential',
                'verbose_name_plural': 'integration credentials',
                'ordering': ['client', 'provider', 'name'],
                'unique_together': {('client', 'provider', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DirectAdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_username', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('disk_quota', models.IntegerField(blank=True, help_text='Disk quota in MB', null=True)),
                ('disk_used', models.IntegerField(blank=True, help_text='Disk used in MB', null=True)),
                ('bandwidth_quota', models.IntegerField(blank=True, help_text='Bandwidth quota in MB', null=True)),
                ('bandwidth_used', models.IntegerField(blank=True, help_text='Bandwidth used in MB', null=True)),
                ('email_accounts', models.IntegerField(default=0)),
                ('databases', models.IntegerField(default=0)),
                ('subdomains', models.IntegerField(default=0)),
                ('is_suspended', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directadmin_accounts', to='services.servicesubscription')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directadmin_accounts', to='integrations.integrationcredential')),
            ],
            options={
                'verbose_name': 'DirectAdmin account',
                'verbose_name_plural': 'DirectAdmin accounts',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='cPanelAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpanel_username', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('disk_quota', models.IntegerField(blank=True, help_text='Disk quota in MB', null=True)),
                ('disk_used', models.IntegerField(blank=True, help_text='Disk used in MB', null=True)),
                ('bandwidth_quota', models.IntegerField(blank=True, help_text='Bandwidth quota in MB', null=True)),
                ('bandwidth_used', models.IntegerField(blank=True, help_text='Bandwidth used in MB', null=True)),
                ('email_accounts', models.IntegerField(default=0)),
                ('databases', models.IntegerField(default=0)),
                ('subdomains', models.IntegerField(default=0)),
                ('is_suspended', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpanel_accounts', to='services.servicesubscription')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpanel_accounts', to='integrations.integrationcredential')),
            ],
            options={
                'verbose_name': 'cPanel account',
                'verbose_name_plural': 'cPanel accounts',
                'ordering': ['domain'],
            },
        ),
    ]
