# Generated by Django 6.0.1 on 2026-01-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationcredential',
            name='provider',
            field=models.CharField(choices=[('cpanel', 'cPanel'), ('directadmin', 'DirectAdmin'), ('cloudflare', 'Cloudflare'), ('namecheap', 'Namecheap'), ('aws', 'AWS'), ('digitalocean', 'DigitalOcean'), ('other', 'Other')], max_length=50),
        ),
    ]
