# Generated by Django 6.0.1 on 2026-01-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integrationcredential_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('whatsapp', 'WhatsApp Business API'), ('namecheap', 'Namecheap'), ('cloudflare', 'Cloudflare'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=50, unique=True)),
                ('name', models.CharField(help_text='Configuration name', max_length=255)),
                ('api_url', models.URLField(blank=True, help_text='API base URL', null=True)),
                ('encrypted_api_key', models.TextField(blank=True, help_text='Encrypted API key', null=True)),
                ('encrypted_api_secret', models.TextField(blank=True, help_text='Encrypted API secret', null=True)),
                ('encrypted_access_token', models.TextField(blank=True, help_text='Encrypted access token', null=True)),
                ('config_data', models.JSONField(blank=True, default=dict, help_text='Additional configuration as JSON')),
                ('is_active', models.BooleanField(default=True)),
                ('is_sandbox', models.BooleanField(default=False, help_text='Is this a sandbox/test environment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API configuration',
                'verbose_name_plural': 'API configurations',
                'ordering': ['provider', 'name'],
            },
        ),
    ]
