# Generated by Django 5.2.10 on 2026-02-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_apiconfiguration_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='provider',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp Business API'), ('namecheap', 'Namecheap'), ('cloudflare', 'Cloudflare'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('paynow', 'Paynow'), ('gemini', 'Google Gemini AI'), ('other', 'Other')], max_length=50, unique=True),
        ),
    ]
