# Generated by Django 5.2.10 on 2026-01-25 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reseller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(help_text='Primary area of expertise', max_length=255)),
                ('referral_bonus_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('active_referrals', models.IntegerField(default=0)),
                ('total_referrals', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='resellerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resellerprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='resellerprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='resellerprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='AgencyReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_description', models.TextField(blank=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='reseller.agencypartner')),
                ('referred_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('reseller', 'Reseller'), ('agency', 'Agency Partner'), ('technology', 'Technology Alliance')], default='reseller', max_length=20)),
                ('tier', models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Profile',
                'verbose_name_plural': 'Partner Profiles',
            },
        ),
        migrations.AddField(
            model_name='agencypartner',
            name='partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_data', to='reseller.partnerprofile'),
        ),
        migrations.AddField(
            model_name='resellerprofile',
            name='partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reseller_data', to='reseller.partnerprofile'),
        ),
        migrations.CreateModel(
            name='TechnologyAlliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('integration_type', models.CharField(help_text='Type of integration (API, Plugin, etc.)', max_length=255)),
                ('api_key', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('revenue_share_percentage', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('partner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technology_data', to='reseller.partnerprofile')),
            ],
        ),
    ]
