# Generated by Django 5.2.10 on 2026-01-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_whmcs_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Service-specific configuration and options'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('hosting', 'Web Hosting'), ('domain', 'Domain Services'), ('development', 'Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('maintenance', 'Maintenance'), ('cloud', 'Cloud Services'), ('other', 'Other')], max_length=50),
        ),
    ]
