# Generated by Django 5.2.10 on 2026-01-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_service_metadata_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingproduct',
            name='hosting_type',
            field=models.CharField(choices=[('shared', 'Shared Hosting'), ('vps', 'VPS Hosting'), ('dedicated', 'Dedicated Server'), ('cloud', 'Cloud Hosting'), ('reseller', 'Reseller Hosting')], default='shared', help_text='Type of hosting package', max_length=20),
        ),
    ]
