# Generated by Django 5.2.10 on 2026-01-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0006_add_hosting_type_to_hosting_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='Full domain name to transfer (e.g., example.com)', max_length=255)),
                ('contact_email', models.EmailField(help_text='Contact email for transfer updates', max_length=254)),
                ('contact_name', models.CharField(help_text="Contact person's name", max_length=255)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50, null=True)),
                ('epp_code', models.CharField(blank=True, help_text='EPP/Authorization code from current registrar', max_length=100, null=True)),
                ('current_registrar', models.CharField(blank=True, help_text='Current domain registrar', max_length=255, null=True)),
                ('admin_email', models.EmailField(blank=True, help_text='Admin email listed in WHOIS (for verification)', max_length=254, null=True)),
                ('owns_domain', models.BooleanField(default=False, help_text='User confirms they own this domain')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('awaiting_epp', 'Awaiting EPP Code'), ('in_progress', 'Transfer In Progress'), ('completed', 'Transfer Completed'), ('failed', 'Transfer Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Additional status information or error messages', null=True)),
                ('update_nameservers', models.BooleanField(default=True, help_text='Update nameservers to our servers after transfer')),
                ('nameserver1', models.CharField(blank=True, max_length=255, null=True)),
                ('nameserver2', models.CharField(blank=True, max_length=255, null=True)),
                ('whois_privacy', models.BooleanField(default=False, help_text='Enable WHOIS privacy after transfer')),
                ('auto_renew', models.BooleanField(default=True, help_text='Enable auto-renewal after transfer')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for staff', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the transfer was completed', null=True)),
                ('client', models.ForeignKey(blank=True, help_text='Associated client (if logged in)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='clients.client')),
            ],
            options={
                'verbose_name': 'domain transfer request',
                'verbose_name_plural': 'domain transfer requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
