# Generated by Django 5.2.10 on 2026-01-25 20:05

import django.db.models.deletion
from django.db import migrations, models


def create_domain_transfer_request_if_not_exists(apps, schema_editor):
    """
    No-op: Table creation is now handled by migration 0010.
    Kept for migration history compatibility on databases where this already ran.
    """
    pass


def reverse_create_domain_transfer_request(apps, schema_editor):
    """Reverse migration - drop the table if it exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute('DROP TABLE IF EXISTS "services_domaintransferrequest" CASCADE;')


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0006_add_hosting_type_to_hosting_product'),
    ]

    operations = [
        migrations.RunPython(
            create_domain_transfer_request_if_not_exists,
            reverse_create_domain_transfer_request,
        ),
    ]
