# Generated by Django 5.2.10 on 2026-01-25 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_add_domain_transfer_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_addon',
            field=models.BooleanField(default=False, help_text='Indicates if this service is an addon to another service'),
        ),
        migrations.AddField(
            model_name='service',
            name='parent_service',
            field=models.ForeignKey(blank=True, help_text='Parent service if this is a service addon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_services', to='services.service'),
        ),
    ]
