# Generated by Django 5.2.10 on 2026-01-25 20:48

from django.db import migrations


def add_recommended_addons_field(apps, schema_editor):
    """
    No-op: Table creation is now handled by migration 0010.
    Kept for migration history compatibility on databases where this already ran.
    """
    pass


def reverse_add_recommended_addons_field(apps, schema_editor):
    """Reverse migration - drop the table if it exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute('DROP TABLE IF EXISTS "services_service_recommended_addons" CASCADE;')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_add_domain_transfer_request'),
    ]

    operations = [
        migrations.RunPython(
            add_recommended_addons_field,
            reverse_add_recommended_addons_field,
        ),
    ]
