# Generated by Django 5.2.10 on 2026-01-25 20:48

from django.db import migrations


def add_recommended_addons_field(apps, schema_editor):
    """
    Safely add the recommended_addons ManyToManyField to Service model.
    This handles cases where a previous migration attempt may have partially 
    created the intermediary table or PostgreSQL type.
    """
    connection = schema_editor.connection
    table_name = 'services_service_recommended_addons'
    type_name = 'services_service_recommended_addons'
    
    # Check if the intermediary table already exists
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            );
        """, [table_name])
        table_exists = cursor.fetchone()[0]
    
    if table_exists:
        # Table already exists, nothing to do
        return
    
    # Check and clean up any orphaned PostgreSQL type that might exist
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM pg_type t
                JOIN pg_namespace n ON t.typnamespace = n.oid
                WHERE n.nspname = 'public' 
                AND t.typname = %s
            );
        """, [type_name])
        type_exists = cursor.fetchone()[0]
        
        if type_exists:
            # Drop the orphaned type before creating the table
            cursor.execute(f'DROP TYPE IF EXISTS "{type_name}" CASCADE;')
    
    # Also check and clean up any orphaned sequences that might exist
    sequence_name = f'{table_name}_id_seq'
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM pg_sequences 
                WHERE schemaname = 'public' 
                AND sequencename = %s
            );
        """, [sequence_name])
        sequence_exists = cursor.fetchone()[0]
        
        if sequence_exists:
            # Drop the orphaned sequence before creating the table
            cursor.execute(f'DROP SEQUENCE IF EXISTS "{sequence_name}" CASCADE;')
    
    # Now create the ManyToMany intermediary table using raw SQL
    with connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE "services_service_recommended_addons" (
                "id" bigserial NOT NULL PRIMARY KEY,
                "from_service_id" bigint NOT NULL REFERENCES "services_service" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                "to_service_id" bigint NOT NULL REFERENCES "services_service" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
            );
        """)
        # Create unique constraint for the relationship
        cursor.execute("""
            ALTER TABLE "services_service_recommended_addons" 
            ADD CONSTRAINT "services_service_recommended_addons_unique" 
            UNIQUE ("from_service_id", "to_service_id");
        """)
        # Create indexes for the foreign keys
        cursor.execute("""
            CREATE INDEX "services_service_recommended_addons_from_service_id_idx" 
            ON "services_service_recommended_addons" ("from_service_id");
        """)
        cursor.execute("""
            CREATE INDEX "services_service_recommended_addons_to_service_id_idx" 
            ON "services_service_recommended_addons" ("to_service_id");
        """)


def reverse_add_recommended_addons_field(apps, schema_editor):
    """Reverse migration - drop the table if it exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute('DROP TABLE IF EXISTS "services_service_recommended_addons" CASCADE;')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_add_domain_transfer_request'),
    ]

    operations = [
        migrations.RunPython(
            add_recommended_addons_field,
            reverse_add_recommended_addons_field,
        ),
    ]
