# Generated by Django 5.2.10 on 2026-01-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_service_recommended_addons_domaintransferrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price (e.g., cPanel license, domain registry cost)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price to clients', max_digits=10, null=True),
        ),
    ]
