# Generated by Django 5.2.10 on 2026-02-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_add_vps_dedicated_specs'),
        ('services', '0011_service_cost_price_alter_service_base_price'),
    ]

    operations = [
    ]
