# Generated by Django 5.2.10 on 2026-02-14 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('services', '0012_merge_20260214_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Basic Website, E-commerce Store', max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_app', 'Mobile App Development'), ('ecommerce', 'E-Commerce'), ('seo', 'SEO & Marketing'), ('design', 'Graphic Design'), ('branding', 'Branding'), ('maintenance', 'Maintenance & Support'), ('custom', 'Custom Project')], default='web_development', max_length=30)),
                ('deliverables', models.JSONField(blank=True, default=list, help_text="List of deliverables included (e.g., ['5-page website', 'Contact form', 'SEO setup'])")),
                ('estimated_duration_days', models.IntegerField(default=30, help_text='Estimated project duration in days')),
                ('max_revisions', models.IntegerField(default=3, help_text='Maximum number of revisions included')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base package price', max_digits=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'project package',
                'verbose_name_plural': 'project packages',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount due upon completion of this milestone', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='deliverables',
            field=models.JSONField(blank=True, default=list, help_text='List of deliverables for this milestone'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='is_billable',
            field=models.BooleanField(default=False, help_text='Whether this milestone triggers a payment'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='payment_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Payment Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='not_applicable', help_text='Payment status for billable milestones', max_length=20),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='Task that must be completed before this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='services.projecttask'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Task priority level', max_length=20),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount spent so far', max_digits=10),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total project budget', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Direct client reference for easier querying', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client'),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='project_type',
            field=models.CharField(choices=[('web_development', 'Web Development'), ('mobile_app', 'Mobile App Development'), ('ecommerce', 'E-Commerce'), ('seo', 'SEO & Marketing'), ('design', 'Graphic Design'), ('branding', 'Branding'), ('maintenance', 'Maintenance & Support'), ('custom', 'Custom Project')], default='web_development', help_text='Type/category of project', max_length=30),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='project_package',
            field=models.ForeignKey(blank=True, help_text='Package/tier this project is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='services.projectpackage'),
        ),
    ]
