# Generated by Django 5.2.10 on 2026-02-16 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_projectpackage_projectmilestone_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFreeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_value', models.PositiveIntegerField(help_text="Number of time units the free period lasts (e.g., 2 for '2 months')")),
                ('duration_unit', models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], default='months', help_text='Unit of the free period (days, months, or years)', max_length=10)),
                ('description', models.CharField(blank=True, help_text="Optional description override (e.g., 'Free shared hosting for 2 months')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(help_text='The project package this free service belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='free_services', to='services.projectpackage')),
                ('service', models.ForeignKey(help_text='The service offered for free (e.g., Web Hosting, Domain Registration)', on_delete=django.db.models.deletion.CASCADE, related_name='free_in_packages', to='services.service')),
            ],
            options={
                'verbose_name': 'package free service',
                'verbose_name_plural': 'package free services',
                'ordering': ['package', 'service'],
                'unique_together': {('package', 'service')},
            },
        ),
    ]
